export const STAKE_DEPOSITE_ACTION_REQUEST = 'STAKE_DEPOSITE_ACTION_REQUEST';
export const STAKE_DEPOSITE_ACTION_SUCCESS = 'STAKE_DEPOSITE_ACTION_SUCCESS';
export const STAKE_DEPOSITE_ACTION_FAIL = 'STAKE_DEPOSITE_ACTION_FAIL';

export const GET_STAKE_DETAIL_ACTION_REQUEST =
	'GET_STAKE_DETAIL_ACTION_REQUEST';
export const GET_STAKE_DETAIL_ACTION_SUCCESS =
	'GET_STAKE_DETAIL_ACTION_SUCCESS';
export const GET_STAKE_DETAIL_ACTION_FAIL = 'GET_STAKE_DETAIL_ACTION_FAIL';

export const GET_BALANCE_VALUE_ACTION_REQUEST =
	'GET_BALANCE_VALUE_ACTION_REQUEST';
export const GET_BALANCE_VALUE_ACTION_SUCCESS =
	'GET_BALANCE_VALUE_ACTION_SUCCESS';
export const GET_BALANCE_VALUE_ACTION_FAIL = 'GET_BALANCE_VALUE_ACTION_FAIL';

export interface StakingState {
	isLoading: boolean;
	transaction: string;
	isLoadingTransaction: boolean;
	stakeDetail: {
		staked: number;
		unstaked: number;
		reward: number;
	};
    currentBalanceValue: string | number;
}
